In [1]:
import numpy as np

In [2]:
li=[1,2,3,4]

In [3]:
type(li)

list

In [4]:
x=np.array(li)

In [5]:
x

array([1, 2, 3, 4])

In [6]:
type(x)

numpy.ndarray

# Handling Missing Data

In [7]:
import pandas as pd
import numpy as np

In [8]:
data1=np.array([1, None,2,3])

In [9]:
data1

array([1, None, 2, 3], dtype=object)

In [12]:
%timeit np.arange(1E6, dtype=int).sum()      #timeit fn. gives time required to do the task 

2.23 ms ± 85.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit np.arange(1E6, dtype=object).sum()

80.4 ms ± 3.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Data1.sum()

Pandas does not use None in its numerical array

To perform any function we have to remove nan

In [13]:
data2= np.array([1,np.nan,3,4])

In [14]:
data2

array([ 1., nan,  3.,  4.])

In [15]:
type(data2)

numpy.ndarray

In [16]:
# 1 + None

In [17]:
1 + np.nan

nan

In [18]:
1 * np.nan

nan

In [19]:
0 * np.nan

nan

# NaN and None in pandas

In [29]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [30]:
x= pd.Series(range(2), dtype=int)

In [31]:
x

0    0
1    1
dtype: int32

In [32]:
x[0] = None

In [33]:
x

0    NaN
1    1.0
dtype: float64

In [34]:
# pandas automatically converts the None to NaN value

type class

1. floating ----- no change-------np.nan
2. object --------no change-------np.nan or None
3. integer -------cast to float64-----np.nan
4. boolean-------cast to object -----None or np.nan

In [35]:
y = pd.Series(range(5), dtype=object)

In [36]:
y

0    0
1    1
2    2
3    3
4    4
dtype: object

In [37]:
y[0] = None

In [38]:
y

0    None
1       1
2       2
3       3
4       4
dtype: object

# pandas nullable dtypes

In [41]:
pd.Series([1,np.nan,2,None,pd.NA], dtype='Int32')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

In [29]:
pd.Series([1,np.nan,2,None,pd.NA], dtype='Int64')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int64

In [32]:
pd.Series([1,np.nan,2,None,pd.NA], dtype=object)

0       1
1     NaN
2       2
3    None
4    <NA>
dtype: object

In [41]:
pd.Series([1,np.nan,2,None], dtype=float)

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

# Operating on null values

### isnull

The isnull() method returns a DataFrame object where all the values are replaced with a Boolean value True for NULL values, and otherwise False.

In [51]:
data=pd.Series([1,np.nan,'hello',None])

In [52]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [53]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

### notnull

The notnull() method returns a DataFrame object where all the values are replaced with a Boolean value True for NOT NULL values, and otherwise False.

In [54]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [55]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [56]:
data[data.notnull()]

0        1
2    hello
dtype: object

### dropna

The dropna() method removes the rows that contains NULL values.

In [57]:
data=pd.Series([1,np.nan,'hello',None])

In [58]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [59]:
data.dropna()

0        1
2    hello
dtype: object

In [60]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

### fillna

The fillna() method replaces the NULL values with a specified value.

In [64]:
data=pd.Series([1,np.nan,'hello',None,NA])

NameError: name 'NA' is not defined

In [62]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [63]:
data.fillna(0)

0        1
1        0
2    hello
3        0
dtype: object